export enum Pages {
  HOME = "HOME",
  COURSES = "COURSES",
  SERVICES = "SERVICES",
  REVIEWS = "REVIEWS",
  CONTACTS = "CONTACTS",
}

export enum WidgetTypes {
  BASE_WIDGET = "BASE_WIDGET",
  TEXT_WIDGET = "TEXT_WIDGET",
  IMAGE_WIDGET = "IMAGE_WIDGET",
  COURSE_SCHEDULE_WIDGET = "COURSE_SCHEDULE_WIDGET",
  FEATURES_WIDGET = "FEATURES_WIDGET",
  COURSE_IMAGES_WIDGET = "COURSE_IMAGES_WIDGET",
  COURSE_PROGRAM_WIDGET = "COURSE_PROGRAM_WIDGET",
}