export enum WidgetTypes {
  BASE_WIDGET = "BASE_WIDGET",
  TEXT_WIDGET = "TEXT_WIDGET",
  IMAGE_WIDGET = "IMAGE_WIDGET",
  COURSE_SCHEDULE_WIDGET = "COURSE_SCHEDULE_WIDGET",
  FEATURES_WIDGET = "FEATURES_WIDGET",
  COURSE_IMAGES_WIDGET = "COURSE_IMAGES_WIDGET",
  COURSE_PROGRAM_WIDGET = "COURSE_PROGRAM_WIDGET",
}

export enum IconTypes {
  CHECK_MARK = "CM",
}

export enum Pages {
  INIT = "INIT",
  OVERVIEW = "OVERVIEW",
  COURSES = "COURSES",
  REVIEWS = "REVIEWS",
  STUDENTS_WORK = "STUDENTS_WORK",
}

export enum CoursesSections {
  INIT = "INIT",
  COURSES_LIST = "COURSES_LIST",
  TIMETABLE = "TIMETABLE",
  ANALYTICS = "ANALYTICS",
}
